<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Filter Include="Source files">
      <UniqueIdentifier>{93a15ece-7f5f-4bdf-bf39-d7e1bad5a146}</UniqueIdentifier>
      <Extensions>cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx</Extensions>
    </Filter>
    <Filter Include="Header files">
      <UniqueIdentifier>{e7a9b271-9440-4f09-99ee-2b7cb662d500}</UniqueIdentifier>
      <Extensions>h;hpp;hxx;hm;inl;inc;xsd</Extensions>
    </Filter>
    <Filter Include="Resource files">
      <UniqueIdentifier>{33cf5258-aa9e-46e6-a75a-177848585d7a}</UniqueIdentifier>
      <Extensions>rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe;resx;tiff;tif;png;wav</Extensions>
    </Filter>
    <Filter Include="Source files\Device-specific files">
      <UniqueIdentifier>{677bcf68-53a9-476e-9f70-6e1454abf2a6}</UniqueIdentifier>
    </Filter>
    <Filter Include="Header files\Device-specific files">
      <UniqueIdentifier>{3fdc396c-0b61-4e79-9400-e812814a79ce}</UniqueIdentifier>
    </Filter>
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="..\main.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\misc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\queue.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\counter8.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\delay.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\eeprom.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\gps.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\gsm.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\i8.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\ia8.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\io16.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\o8.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\onewire.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\plc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\pwm.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\pilot_comm.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\pilot_usart.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\rtc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\slcd.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\spi.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\test.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\usart.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_adc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_bkp.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_can.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_cec.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_crc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_dac.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_dbgmcu.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_dma.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_exti.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_flash.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_fsmc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_gpio.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_i2c.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_it.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_iwdg.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_pwr.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_rcc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_rtc.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_sdio.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_spi.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_tim.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_usart.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\stm32f10x_wwdg.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="..\system_stm32f10x.c">
      <Filter>Source files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\CMSIS\CM3\CoreSupport\core_cm3.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\CMSIS\CM3\DeviceSupport\ST\STM32F10x\system_stm32f10x.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\misc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_adc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_bkp.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_can.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_cec.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_crc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_dac.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_dbgmcu.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_dma.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_exti.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_flash.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_fsmc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_gpio.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_i2c.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_iwdg.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_pwr.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_rcc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_rtc.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_sdio.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_spi.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_tim.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_usart.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\src\stm32f10x_wwdg.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
    <ClCompile Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\Startup\startup_stm32f10x_hd.c">
      <Filter>Source files\Device-specific files</Filter>
    </ClCompile>
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="..\core_cm3.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\core_cmFunc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\core_cmInstr.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\misc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\queue.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\common_base.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\counter8.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\delay.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\eeprom.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\gpio_config.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\gps.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\gsm.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\i8.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\ia8.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\io16.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\io_stm.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\it_callback.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\o8.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\onewire.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\plc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\pwm.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\pilot_comm.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\pilot_usart.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\rtc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\slcd.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\spi.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\test.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\tty_commands.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\types.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\usart.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_adc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_bkp.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_can.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_cec.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_conf.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_crc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_dac.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_dbgmcu.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_dma.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_exti.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_flash.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_fsmc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_gpio.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_i2c.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_it.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_iwdg.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_pwr.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_rcc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_rtc.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_sdio.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_spi.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_tim.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_type.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_usart.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32f10x_wwdg.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\stm32_conf.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="..\system_stm32f10x.h">
      <Filter>Header files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\CMSIS\CM3\CoreSupport\core_cm3.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\CMSIS\CM3\DeviceSupport\ST\STM32F10x\stm32f10x.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\CMSIS\CM3\DeviceSupport\ST\STM32F10x\system_stm32f10x.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\misc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_adc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_bkp.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_can.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_cec.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_crc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_dac.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_dbgmcu.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_dma.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_exti.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_flash.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_fsmc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_gpio.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_i2c.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_iwdg.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_pwr.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_rcc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_rtc.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_sdio.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_spi.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_tim.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_usart.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
    <ClInclude Include="C:\Users\amd\AppData\Local\VisualGDB\EmbeddedBSPs\arm-eabi\com.sysprogs.arm.stm32\STM32F1xxxx\STM32F10x_StdPeriph_Driver\inc\stm32f10x_wwdg.h">
      <Filter>Header files\Device-specific files</Filter>
    </ClInclude>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\stm32.mak">
      <Filter>Source files\Device-specific files</Filter>
    </None>
  </ItemGroup>
</Project>